### ISSUE TITLE
Data streaming

### ISSUE THREAD

**Issue by mwlock** [dadul96/Siglent_SDS1202X-E_VISA_MATLAB#1]
Hey !

Quick question, I am looking to record 2 minutes' worth of samples.

Since the oscilloscope cannot record for two minutes,  I was wondering if this tool could be used to stream / record data as the oscilloscope is sampling?

**Comment by dadul96** [comment]
Hello.
Unfortunately, it is not possible to stream live data over to the PC. With this tool and the device's SCPI commands in general, you can only store the data from the currently displayed signal. What you can do is poll the currently displayed waveform for 2min and store it on the PC, but then you will lose some "frames" of data in between the requests. (I don't know your application, but maybe you do not need 2min of constant data streaming.)

**Comment by mwlock** [comment]
Unfortunately, we needed 2 continuous minutes.  Ulltimately we could not use your tool and wrote a script to loop through the frames in history mode and save them all to a flash drive. But still, many thanks for the answer and for providing such a great tool!
