### ISSUE TITLE
Different voltage measurements between Scope and Matlab

### ISSUE THREAD

**Issue by seackone** [dadul96/Siglent_SDS1202X-E_VISA_MATLAB#2]
I was using your scripts to transfer the data from scope (SDS2102X-Plus) into matlab. I works very well but I can see a slightly difference between the measured voltage amplitude at the scope and with the received data in matlab. The equation (also within the programmers guide of the scope) is as followed:

dataOut(i) = data(i)*(vDiv/25)-offs;

Im wondering about the 25. Why is there no dependency between resolution (8bit or 10bit) and vertical scaling (V/div)? 

For example:
Im measuring at the scope an Pk-Pk voltage of a simple sine signal of 506mV. Resolution is 8 bit and the vertical resolution is 70mV/div and no offset.

![image](https://user-images.githubusercontent.com/38973144/213447181-30508cfb-100b-490d-995b-743b6bee9be3.png)

If I load the data into matlab, my pk-pk voltage is at 604mV.

![image](https://user-images.githubusercontent.com/38973144/213447930-cad0d007-f394-49ac-b2c0-ed6a4cf26864.png)

Do you have any idea, why there is such a difference? I think the equation would be better with something like:

dataOut(i) = data(i)*(vDiv * 8/2^8)-offs; 

...for 8 bit. the reciprocal of 8/2^8 is 32 and not 25. but even then, i have not the same results as on the scope.

![image](https://user-images.githubusercontent.com/38973144/213448673-824dd374-baf3-4a88-8aaf-834ff9085dc7.png)

What are your experiences with that?

**Comment by dadul96** [comment]
To be on the same page, I would like to mention that we have different scopes with different implementations of the _"WAVeform"_ command. 

My scope (SDS1000X-E series) uses the formula you have already mentioned above: `voltage value (V) = code value * (vdiv / 25) - voffset`

Your scope (SDS2000X Plus series) uses this formula: `voltage value (V) = code value * (vdiv / code_per_div) - voffset`
(You can get the _"code_per_div"_ value by using the _"WAVeform:PREamble"_ command.)

There is a very nice example code starting at page 630 in the [programming guide](https://siglentna.com/download/29924/?tmstv=1674097158).

(Maybe you looked at the programming guide of the end-of-life product (SDS2000X series) which basically shows the same instructions as for my scope.)

**Comment by seackone** [comment]
Good morning Daniel,
thank you very much for your very fast response! That helps a lot, i really appreciate it! Yes you are absolutely right, I was using the [programming guide](https://int.siglent.com/u_file/document/SDS1000%20Series&SDS2000X&SDS2000X-E_ProgrammingGuide_PG01-E02D.pdf) with the factor 25 (still dont know where it comes from and why they dont use anything referring to voltage per bit), which is probably not valid for the plus series. In your referred programming guide on page 561, there is a factor of 30 for our device and now it works correct. It was the easiest way to change just the number.. I also had to upgrade to the newest firmware to use the new programming commands but there are still some bugs left. For example if I want to set the memory mode of the scope to a fixed sampling rate:

_-> :ACQuire:MMANagement?
<- AUTO
-> :ACQuire:MMANagement FSRate
-> SYST:ERR?
<- 0,"No error"
-> :ACQuire:MMANagement?
<- AUTO_

.. it does not work but I also dont have any errors. Anyways, thats an other topic and not important. Thank you very much for your support again and great work on the scripts!
